# https://docs.github.com/en/actions/using-workflows/about-workflows
# A matrix strategy lets you use variables in a single job definition to automatically create multiple job runs that are based on the combinations of the variables. 
# For example, you can use a matrix to test your code in multiple operating systems.
# different machines: https://docs.github.com/en/actions/using-jobs/choosing-the-runner-for-a-job
# https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs

name: echo messsages

on: push #all kind of actions

    inputs:
      tag:
        description: Tag to run
        required: true
        type: choice
        options:
          - '@routes'
          - '@appJs'
          - '@smoke'
      n:
        description: Number of times to repeat the test
        required: false
        default: '1'
        type: string

jobs:
  AllPushes:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - run: echo "ğŸ–¥ï¸ The workflow is to show various echo messages and variables"
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Print workflow inputs
        run: |
          echo Running tests with tag: ${{ github.event.inputs.tag }}
          echo for ${{ github.event.inputs.n }} times

      - run: echo "ğŸ This job's status is ${{ job.status }}."
