
name: Echo messsages

on: push

jobs:
  EchoMessagesJob:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - run: echo "ğŸ–¥ï¸ The workflow is to show various echo messages and variables"
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      # - run: echo "Workspace location is ${{ RUNNER_WORKSPACE }}"

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - run: echo "ğŸ This job's status is ${{ job.status }}."
